export const backupData = {
  "crew": [
    {
      "id": 1,
      "name": "Petr Heitzer",
      "ii": "PH",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 260,
      "phone": "721250034",
      "email": "petr.heitzer@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Petr Heitzer",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: CH"
    },
    {
      "id": 2,
      "name": "Adam Ferda",
      "ii": "AF",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "776601333",
      "email": "adamferdis8@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Adam Ferda",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 3,
      "name": "Adam Vlček",
      "ii": "AV",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "731643198",
      "email": "adik.vlcek@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Adam Vlček",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "18 let | Role: Crew"
    },
    {
      "id": 4,
      "name": "Adam Votoček",
      "ii": "AV",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "731825030",
      "email": "adam.votocek123456@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Adam Votoček",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "17 let | Role: Crew"
    },
    {
      "id": 5,
      "name": "Adam Dlouhý",
      "ii": "AD",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "732120128",
      "email": "adamdlouhy14@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Adam Dlouhý",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 6,
      "name": "Albert Cibulka",
      "ii": "AC",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "774992536",
      "email": "albert.cibulka1@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Albert Cibulka",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 7,
      "name": "Aleš Burger",
      "ii": "AB",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [],
      "events": 0,
      "rate": 240,
      "phone": "602366903",
      "email": "ales.burger@nextlevel.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Aleš Burger",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: COO"
    },
    {
      "id": 8,
      "name": "Alexej Sato",
      "ii": "AS",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "721964943",
      "email": "aleschateau23@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Alexej Sato",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 9,
      "name": "Barbora Halušková",
      "ii": "BH",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 260,
      "phone": "734276604",
      "email": "barbora.haluskova@jchp.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Barbora Halušková",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: CH"
    },
    {
      "id": 10,
      "name": "Barbora Štěrbová",
      "ii": "BŠ",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 240,
      "phone": "775188400",
      "email": "barbora.sterbova@nextlevel.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Barbora Štěrbová",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: COO"
    },
    {
      "id": 11,
      "name": "Dan Šimůnek",
      "ii": "DŠ",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "776295308",
      "email": "dannysimunek@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Dan Šimůnek",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 12,
      "name": "Daniel Nejez",
      "ii": "DN",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [],
      "events": 0,
      "rate": 240,
      "phone": "773981995",
      "email": "daniel.nejez@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Daniel Nejez",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: COO"
    },
    {
      "id": 13,
      "name": "David Kostohryz",
      "ii": "DK",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "723039442",
      "email": "davitekk.dk@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "David Kostohryz",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 14,
      "name": "David Kříž",
      "ii": "DK",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "728060414",
      "email": "kriz.david2003@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "David Kříž",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 15,
      "name": "David Mayer",
      "ii": "DM",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "722141229",
      "email": "majlad@centrum.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "David Mayer",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 16,
      "name": "David Urubek",
      "ii": "DU",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "777956211",
      "email": "david.urubek@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "David Urubek",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 17,
      "name": "David Hybler",
      "ii": "DH",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "603498517",
      "email": "davidhybler878@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "David Hybler",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 18,
      "name": "David Šarman",
      "ii": "DŠ",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "601540622",
      "email": "davidsharman@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "David Šarman",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 19,
      "name": "Dominik Mládek",
      "ii": "DM",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "775162362",
      "email": "dominik.mladek@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Dominik Mládek",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 20,
      "name": "Dominik Hofer",
      "ii": "DH",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "774636848",
      "email": "domcahofer@icloud.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Dominik Hofer",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Zkušenost s produkcí, dekorace, pracant | Role: Crew"
    },
    {
      "id": 21,
      "name": "Erik Cvopa",
      "ii": "EC",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "907093519",
      "email": "erik.cvopa@nextlevel.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Erik Cvopa",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "SK | Role: Crew"
    },
    {
      "id": 22,
      "name": "Filip Josífko",
      "ii": "FJ",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [],
      "events": 0,
      "rate": 240,
      "phone": "728136087",
      "email": "filip.josifko@nextlevel.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Filip Josífko",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: COO"
    },
    {
      "id": 23,
      "name": "Ivana Kalendová",
      "ii": "IK",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 260,
      "phone": "776812929",
      "email": "ivana.kalendova@nextlevel.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Ivana Kalendová",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: CH"
    },
    {
      "id": 24,
      "name": "Jakub Havlas",
      "ii": "JH",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [
        "Ridic"
      ],
      "events": 0,
      "rate": 200,
      "phone": "702122367",
      "email": "jakub.havlas@oavin.eu",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Jakub Havlas",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "18 let. s řidičákem v pohodě i s dodávkou | Role: Crew"
    },
    {
      "id": 25,
      "name": "Jakub Choutka",
      "ii": "JC",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 260,
      "phone": "602286533",
      "email": "jakub.choutka@jchp.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Jakub Choutka",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: CH"
    },
    {
      "id": 26,
      "name": "Jakub Karhánek",
      "ii": "JK",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 240,
      "phone": "731872106",
      "email": "jakub.karhanek@nextlevel.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Jakub Karhánek",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: COO"
    },
    {
      "id": 27,
      "name": "Jakub Škorec",
      "ii": "JŠ",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [],
      "events": 0,
      "rate": 240,
      "phone": "770131141",
      "email": "skorec.jakub@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Jakub Škorec",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: COO"
    },
    {
      "id": 28,
      "name": "Jakub Trojan",
      "ii": "JT",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "730895585",
      "email": "trojjjja@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Jakub Trojan",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 29,
      "name": "Jakub Balzer",
      "ii": "JB",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "773671352",
      "email": "dark.jimmy@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Jakub Balzer",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 30,
      "name": "Jan Dubský",
      "ii": "JD",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "605956257",
      "email": "honza.dubsky@post.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Jan Dubský",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 31,
      "name": "Jan Foglar",
      "ii": "JF",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "607930261",
      "email": "Foglarjan@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Jan Foglar",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 32,
      "name": "Jan Kaliberka",
      "ii": "JK",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "602393131",
      "email": "hkaliberka@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Jan Kaliberka",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 33,
      "name": "Jan Kolda",
      "ii": "JK",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "733456722",
      "email": "jankolda78@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Jan Kolda",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 34,
      "name": "Jan Ledvina",
      "ii": "JL",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "737360936",
      "email": "ledvinajan06@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Jan Ledvina",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 35,
      "name": "Jan Parásek",
      "ii": "JP",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "777898294",
      "email": "parasek.jan1@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Jan Parásek",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 36,
      "name": "Jan Pěkný",
      "ii": "JP",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "774437047",
      "email": "hamespekny@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Jan Pěkný",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 37,
      "name": "Jan Sickmüller",
      "ii": "JS",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "721346763",
      "email": "jan.sickmuller@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Jan Sickmüller",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 38,
      "name": "Jan Steininger",
      "ii": "JS",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "721170811",
      "email": "hsteininger14@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Jan Steininger",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 39,
      "name": "Jan Fendrych",
      "ii": "JF",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "739372656",
      "email": "jf81reborn@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Jan Fendrych",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 40,
      "name": "Jaroslav Dvořák",
      "ii": "JD",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "702040361",
      "email": "J.dvorak095@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Jaroslav Dvořák",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 41,
      "name": "Jaroslav Macháč",
      "ii": "JM",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "777092598",
      "email": "machac.jrslv@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Jaroslav Macháč",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 42,
      "name": "Jiří Mihalo",
      "ii": "JM",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "792202444",
      "email": "jiri.mihalo@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Jiří Mihalo",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 43,
      "name": "Jiří Rozehnal",
      "ii": "JR",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "728684122",
      "email": "rozexxx1@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Jiří Rozehnal",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 44,
      "name": "Josef Bulín",
      "ii": "JB",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "777797230",
      "email": "josef.bulin@ekolo.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Josef Bulín",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 45,
      "name": "Josef Fajta",
      "ii": "JF",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 240,
      "phone": "603100007",
      "email": "josef.fajta@nextlevel.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Josef Fajta",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: COO"
    },
    {
      "id": 46,
      "name": "Kamil Kabes",
      "ii": "KK",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "725297652",
      "email": "dzamilos@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Kamil Kabes",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 47,
      "name": "Kamil Vocetka",
      "ii": "KV",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [],
      "events": 0,
      "rate": 240,
      "phone": "733654986",
      "email": "kamil.vocetka@nextlevel.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Kamil Vocetka",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: COO"
    },
    {
      "id": 48,
      "name": "Karolína Baňková",
      "ii": "KB",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 240,
      "phone": "723831868",
      "email": "karolina.bankova@jchp.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Karolína Baňková",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: COO"
    },
    {
      "id": 49,
      "name": "Katarina Kubíčková",
      "ii": "KK",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 240,
      "phone": "775763103",
      "email": "katarina.kubickova@nextlevel.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Katarina Kubíčková",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: COO"
    },
    {
      "id": 50,
      "name": "Klára Bartošová",
      "ii": "KB",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "608084988",
      "email": "bartosova-klara@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Klára Bartošová",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Slečna | Role: Crew"
    },
    {
      "id": 51,
      "name": "Ladislav Krajsa",
      "ii": "LK",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 240,
      "phone": "777671522",
      "email": "Ladislav.krajsa@nextlevel.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Ladislav Krajsa",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: COO"
    },
    {
      "id": 52,
      "name": "Lucia Tóthová",
      "ii": "LT",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "774576973",
      "email": "bosorkaaa@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Lucia Tóthová",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 53,
      "name": "Lukáš Dlabal",
      "ii": "LD",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "723466258",
      "email": "dlabal.luk@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Lukáš Dlabal",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 54,
      "name": "Lukáš Linhatr",
      "ii": "LL",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "730512265",
      "email": "lukef@post.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Lukáš Linhatr",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 55,
      "name": "Lukáš Petričák",
      "ii": "LP",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "723898840",
      "email": "lukaspetricak12@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Lukáš Petričák",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 56,
      "name": "Lukáš Sazima",
      "ii": "LS",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "736121208",
      "email": "lukassazima@email.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Lukáš Sazima",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "30.3 - bydlí v Aši | Role: Crew"
    },
    {
      "id": 57,
      "name": "Lukáš Kovář",
      "ii": "LK",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "703954940",
      "email": "lucker.kovin@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Lukáš Kovář",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Rokytnice | Role: Crew"
    },
    {
      "id": 58,
      "name": "Marcela Siglová",
      "ii": "MS",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 240,
      "phone": "731775584",
      "email": "marcela.siglova@nextlevel.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Marcela Siglová",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: COO"
    },
    {
      "id": 59,
      "name": "Marek Jandus",
      "ii": "MJ",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "731331949",
      "email": "jandus.marek@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Marek Jandus",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 60,
      "name": "Marek Rebros",
      "ii": "MR",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "775603380",
      "email": "rebros.marek@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Marek Rebros",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 61,
      "name": "Martin Jíleček",
      "ii": "MJ",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "607974050",
      "email": "martinbarcaboss@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Martin Jíleček",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 62,
      "name": "Martin Pírek",
      "ii": "MP",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "728949525",
      "email": "pirekmartin74@icloud.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Martin Pírek",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 63,
      "name": "Martin Resl",
      "ii": "MR",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "606075353",
      "email": "Reslmartin1892@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Martin Resl",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 64,
      "name": "Martin Jaroš",
      "ii": "MJ",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "777844098",
      "email": "martin.jarosss@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Martin Jaroš",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 65,
      "name": "Martin Kubiska",
      "ii": "MK",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "723650123",
      "email": "Kubiskamartin@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Martin Kubiska",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 66,
      "name": "Martin Řezáč",
      "ii": "MŘ",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "777796065",
      "email": "martinrezac9@icloud.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Martin Řezáč",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "30.3 - Bydlí v Aši | Role: Crew"
    },
    {
      "id": 67,
      "name": "Mathias Hutter",
      "ii": "MH",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "778546985",
      "email": "mathias.hutter299@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Mathias Hutter",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "18 let. | Role: Crew"
    },
    {
      "id": 68,
      "name": "Michal Balner",
      "ii": "MB",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 260,
      "phone": "724969864",
      "email": "michal.balner@hala19.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Michal Balner",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: CH"
    },
    {
      "id": 69,
      "name": "Michal Bodnar",
      "ii": "MB",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "904218130",
      "email": "miso.bodnar@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Michal Bodnar",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "SK | Role: Crew"
    },
    {
      "id": 70,
      "name": "Michal Kovařík",
      "ii": "MK",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "704032300",
      "email": "majkvon@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Michal Kovařík",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 71,
      "name": "Michal Valta",
      "ii": "MV",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 240,
      "phone": "736248524",
      "email": "michal.valta@nextlevel.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Michal Valta",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: COO"
    },
    {
      "id": 72,
      "name": "Michal Král",
      "ii": "MK",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "732688391",
      "email": "mikralchal@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Michal Král",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 73,
      "name": "Michal Stech",
      "ii": "MS",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "731866695",
      "email": "stechmichal23@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Michal Stech",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 74,
      "name": "Miloslav Ponocný",
      "ii": "MP",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "601394637",
      "email": "Milhausakce@post.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Miloslav Ponocný",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 75,
      "name": "Oldřich Soldán",
      "ii": "OS",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "774286064",
      "email": "olin.soldan@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Oldřich Soldán",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 76,
      "name": "Oleg Šlajs",
      "ii": "OŠ",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "735870362",
      "email": "n92rec@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Oleg Šlajs",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 77,
      "name": "Ondra Žak",
      "ii": "OŽ",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "608502350",
      "email": "zak.praha6@email.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Ondra Žak",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 78,
      "name": "Ondřej Strnad",
      "ii": "OS",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "737154409",
      "email": "ondrastrnad11@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Ondřej Strnad",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 79,
      "name": "Ondřej Hlaváč",
      "ii": "OH",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "792301207",
      "email": "hlavacondrej07@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Ondřej Hlaváč",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "17 let. Od Jakuba Ch | Role: Crew"
    },
    {
      "id": 80,
      "name": "Ondřej Šafařík",
      "ii": "OŠ",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "724678672",
      "email": "Ondrasafarik09@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Ondřej Šafařík",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 81,
      "name": "Ondřej Novotný",
      "ii": "ON",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "737176110",
      "email": "novotny.ondra11@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Ondřej Novotný",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "17 let | Role: Crew"
    },
    {
      "id": 82,
      "name": "Patrik Herynek",
      "ii": "PH",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [],
      "events": 0,
      "rate": 240,
      "phone": "774598214",
      "email": "patrik.herynek@nextlevel.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Patrik Herynek",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: COO"
    },
    {
      "id": 83,
      "name": "Patrik Klimáček",
      "ii": "PK",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "904450679",
      "email": "patrik.klimacek@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Patrik Klimáček",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 84,
      "name": "Pavel Hájek",
      "ii": "PH",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 240,
      "phone": "602157566",
      "email": "pavel.hajek@nextlevel.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Pavel Hájek",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: COO"
    },
    {
      "id": 85,
      "name": "Pavel Hroneš",
      "ii": "PH",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "724666562",
      "email": "pavel.hrones@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Pavel Hroneš",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 86,
      "name": "Petr Bayer",
      "ii": "PB",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "601200317",
      "email": "petr.bayer@hala19.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Petr Bayer",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Sklad | Role: Crew"
    },
    {
      "id": 87,
      "name": "Petr Brož",
      "ii": "PB",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "777842717",
      "email": "petr9112@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Petr Brož",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 88,
      "name": "Petr Kohler",
      "ii": "PK",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "774296200",
      "email": "petrkohler25@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Petr Kohler",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 89,
      "name": "Petr Kráčmera",
      "ii": "PK",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 260,
      "phone": "776330713",
      "email": "petr.kracmera@jchp.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Petr Kráčmera",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: CH"
    },
    {
      "id": 90,
      "name": "Petra Hudosová",
      "ii": "PH",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 240,
      "phone": "608577889",
      "email": "hudosova@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Petra Hudosová",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: COO"
    },
    {
      "id": 91,
      "name": "Radek Vrábel",
      "ii": "RV",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "775243199",
      "email": "vrabel.rad@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Radek Vrábel",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 92,
      "name": "Radomír Šimůnek",
      "ii": "RŠ",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [
        "Ridic"
      ],
      "events": 0,
      "rate": 200,
      "phone": "777226704",
      "email": "radomirsimunek@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Radomír Šimůnek",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Řidič B - ročník 83 | Role: Crew"
    },
    {
      "id": 93,
      "name": "Romana Skřivanová",
      "ii": "RS",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 260,
      "phone": "775112922",
      "email": "romana.skrivanova@jchp.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Romana Skřivanová",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Administrativa výplat | Role: CH"
    },
    {
      "id": 94,
      "name": "Samuel Malik",
      "ii": "SM",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "",
      "email": "",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Samuel Malik",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Aktivní bez přístupu | Role: Crew"
    },
    {
      "id": 95,
      "name": "Šimon Karhan",
      "ii": "ŠK",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "728448836",
      "email": "simonkarhan@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Šimon Karhan",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Crew head, rekvizitář u filmu, technik | Role: Crew"
    },
    {
      "id": 96,
      "name": "Šimon Kraus",
      "ii": "ŠK",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "732233342",
      "email": "kraussi@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Šimon Kraus",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 97,
      "name": "Šimon Krejča",
      "ii": "ŠK",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [],
      "events": 0,
      "rate": 240,
      "phone": "728226303",
      "email": "simon.krejca@nextlevel.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Šimon Krejča",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: COO"
    },
    {
      "id": 98,
      "name": "Šimon Přibyl",
      "ii": "ŠP",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "776692424",
      "email": "pribyl.sim@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Šimon Přibyl",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 99,
      "name": "Štěpán Hájek",
      "ii": "ŠH",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "775525053",
      "email": "stepanhajek42@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Štěpán Hájek",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 100,
      "name": "Tadeáš Bohatec",
      "ii": "TB",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 240,
      "phone": "776068994",
      "email": "bohatectadeas@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Tadeáš Bohatec",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: COO"
    },
    {
      "id": 101,
      "name": "Tadeáš Vrtiška",
      "ii": "TV",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "734272788",
      "email": "tadeas.vrtiska@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Tadeáš Vrtiška",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Věk 16+ | Role: Crew"
    },
    {
      "id": 102,
      "name": "Tereza Sklenářová",
      "ii": "TS",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "777779928",
      "email": "teskle@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Tereza Sklenářová",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 103,
      "name": "Tomáš Červeňák",
      "ii": "TČ",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "732477972",
      "email": "tomas.cervenak1234@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Tomáš Červeňák",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 104,
      "name": "Tomáš Jaroš",
      "ii": "TJ",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 240,
      "phone": "777002982",
      "email": "tomas.jaros@nextlevel.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Tomáš Jaroš",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: COO"
    },
    {
      "id": 105,
      "name": "Tomáš Macášek",
      "ii": "TM",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "607999118",
      "email": "tomas.macasek@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Tomáš Macášek",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 106,
      "name": "Tomáš Patrik",
      "ii": "TP",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "727853643",
      "email": "patriktomas@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Tomáš Patrik",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 107,
      "name": "Tomáš Ulík",
      "ii": "TU",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [],
      "events": 0,
      "rate": 240,
      "phone": "605861831",
      "email": "tomas.ulik@nextlevel.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Tomáš Ulík",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: COO"
    },
    {
      "id": 108,
      "name": "Tomáš Kulíšek",
      "ii": "TK",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "605278018",
      "email": "tkulisekt@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Tomáš Kulíšek",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 109,
      "name": "Tomáš Pavlů",
      "ii": "TP",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "777301403",
      "email": "to.pavlu07@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Tomáš Pavlů",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 110,
      "name": "Tonda Tláskal",
      "ii": "TT",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "",
      "email": "",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Tonda Tláskal",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Aktivní bez přístupu | Role: Crew"
    },
    {
      "id": 111,
      "name": "Václava Žák",
      "ii": "VŽ",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "607005037",
      "email": "vasekzakofficial@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Václava Žák",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 112,
      "name": "Valerie Komersová",
      "ii": "VK",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "702206840",
      "email": "V.komersova@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Valerie Komersová",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 113,
      "name": "Veronika Bíšková",
      "ii": "VB",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "606177855",
      "email": "veronikabiskova@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Veronika Bíšková",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Slečna | Role: Crew"
    },
    {
      "id": 114,
      "name": "Viktor Kováč",
      "ii": "VK",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "775066041",
      "email": "viktor.kovac@yahoo.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Viktor Kováč",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 115,
      "name": "Vilém Cibulka",
      "ii": "VC",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "608048650",
      "email": "ciba15v@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Vilém Cibulka",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 116,
      "name": "Vilém Kořínek",
      "ii": "VK",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "607569830",
      "email": "korinek.vilem@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Vilém Kořínek",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 117,
      "name": "Vít Kratochvíl",
      "ii": "VK",
      "bg": "#EEEDFE",
      "fg": "#534AB7",
      "tags": [
        "Ridic"
      ],
      "events": 0,
      "rate": 200,
      "phone": "777809399",
      "email": "kratochvil.vit@gcbrod.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Vít Kratochvíl",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Řidič C+E | Role: Crew"
    },
    {
      "id": 118,
      "name": "Vítězslav Grosman",
      "ii": "VG",
      "bg": "#E6F1FB",
      "fg": "#185FA5",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "602119496",
      "email": "vitezslav.grosman.93@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Vítězslav Grosman",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    },
    {
      "id": 119,
      "name": "Vojtěch Sulanský",
      "ii": "VS",
      "bg": "#FAEEDA",
      "fg": "#854F0B",
      "tags": [],
      "events": 0,
      "rate": 240,
      "phone": "776591904",
      "email": "vojtech.sulansky@nextlevel.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Vojtěch Sulanský",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Produkční | Role: COO"
    },
    {
      "id": 120,
      "name": "Vojtěch Laštovka",
      "ii": "VL",
      "bg": "#EAF3DE",
      "fg": "#3B6D11",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "775603581",
      "email": "vojta.lastovkaa@seznam.cz",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Vojtěch Laštovka",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "17 let | Role: Crew"
    },
    {
      "id": 121,
      "name": "Zbyněk Onderka",
      "ii": "ZO",
      "bg": "#E1F5EE",
      "fg": "#0F6E56",
      "tags": [],
      "events": 0,
      "rate": 200,
      "phone": "722007168",
      "email": "zbynek977@gmail.com",
      "ico": "",
      "dic": "",
      "bank": "",
      "city": "",
      "billingName": "Zbyněk Onderka",
      "billingStreet": "",
      "billingZip": "",
      "billingCity": "",
      "billingCountry": "Česká republika",
      "reliable": true,
      "note": "Role: Crew"
    }
  ],
  "events": [],
  "projects": [],
  "clients": [
    {
      "id": 1,
      "name": "Next Level",
      "city": "Praha",
      "ico": "12345678",
      "street": "Vaclavske namesti 1",
      "zip": "110 00",
      "country": "Česká republika"
    },
    {
      "id": 2,
      "name": "JCHP",
      "city": "Praha",
      "ico": "87654321",
      "street": "Na Prikope 12",
      "zip": "110 00",
      "country": "Česká republika"
    }
  ],
  "timelogs": [],
  "invoices": [],
  "receipts": [],
  "candidates": [
    {
      "id": 1,
      "name": "Pavel Horák",
      "phone": "603 222 333",
      "email": "pavel.horak@email.cz",
      "src": "Tally",
      "calBooked": true,
      "stage": "interview_scheduled",
      "interviewAt": "2026-04-07 14:00",
      "note": "Zájem o víkendové akce, má ŘP."
    },
    {
      "id": 2,
      "name": "Eva Klimešová",
      "phone": "776 444 555",
      "email": "eva.klimesova@email.cz",
      "src": "Tally",
      "calBooked": false,
      "stage": "new",
      "interviewAt": null,
      "note": "Doporučena Kateřinou P."
    },
    {
      "id": 3,
      "name": "Radek Šimek",
      "phone": "602 666 777",
      "email": "radek.simek@email.cz",
      "src": "Tally",
      "calBooked": true,
      "stage": "decision",
      "interviewAt": "2026-04-03 10:00",
      "note": "Zkušenosti z cateringu."
    },
    {
      "id": 4,
      "name": "Tereza Nováčková",
      "phone": "608 888 999",
      "email": "tereza.novackova@email.cz",
      "src": "Tally",
      "calBooked": true,
      "stage": "accepted",
      "interviewAt": "2026-03-28 11:00",
      "note": "Nasazena na první akci."
    }
  ]
} as const;
